var nodeList = [
  "ui_button",
  "ui_dropdown",
  "ui_switch",
  "ui_slider",
  "ui_numeric",
  "ui_text_input",
  "ui_date_picker",
  "ui_colour_picker",
  "ui_form",
  "ui_text",
  "ui_gauge",
  "ui_chart",
//   "ui_audio",
//   "ui_toast",
  "ui_template",
  "ui_worldmap",
];
